### ISSUE TITLE
Change mithril to a more silver-like color.

### ISSUE THREAD

**Issue by kaeza** [minetest-mods/moreores#14]
From the Wikipedia article on [Mithril](https://en.wikipedia.org/wiki/Mithril#Tolkien):

>Mithril! All folk desired it. It could be beaten like copper, and polished like glass; and the Dwarves could make of it a metal, light and yet harder than tempered steel. **Its beauty was like to that of common silver**, but the beauty of mithril did not tarnish or grow dim.

Emphasis mine; quote taken from *The Fellowship of the Ring*.

**Comment by HybridDog** [comment]
Maybe the silver-like look refers to the metal. Mithril is not a metal, l doubt Dwarves can change the proton count of atoms.

**Comment by sofar** [comment]
> It could be beaten like copper,

Sounds like a metal.

> Mithril is a fictional metal

Is the start of said wikipedia article. The dwarves did not change the atoms.

**Comment by Calinou** [comment]
I'd rather keep the current color to avoid "breaking" existing builds (which could look bad if we change the color). That said, I'm open to improving the textures while keeping the blue hue :slightly_smiling_face:
