### ISSUE TITLE
Low maxlevel (especially on mithril tools)

### ISSUE THREAD

**Issue by mgl512** [minetest-mods/moreores#15]
The mithril pickaxe can't dig metal blocks, mese blocks, diamond blocks, obsidian because of its maxlevel 1. Generally, the maxlevel of the tools from moreores should be reviewed in comparison to the ones of the actual minetest_game if a new version is to be released. Metal tools have a maxlevel of 2 and mese and diamond 3. Everything in moreores has a maxlevel of 1.

**Comment by sofar** [comment]
Just submit a patch to make mithril items maxlevel 2, that seems entirely reasonable.

Tin and Silver can stay weak, though.

**Comment by mgl512** [comment]
At maxlevel 2, a mithril pick still can't break a diamond block while mese and diamond picks can because they have a maxlevel of 3 (except the diamond pickaxe, maxlevel 2, but I think it's a mistake in mt_game). Furthermore, mithril tools are slightly slower than mese and diamond on blocks they can break. I think I don't understand the purpose of mithril. Have slow, soft hitting but more durable tools ?

**Comment by HybridDog** [comment]
It should teach players that tools made of ores harder to obtain aren't necessarily better tools.
You also can't make a pick 9 times faster than diamond pick by using diamond blocks for crafting.

**Comment by sofar** [comment]
@mgl512 looks ok, submit PR?

**Comment by mgl512** [comment]
Done. Thought you would have an option to merge the referenced commit without a new pull request.
