### ISSUE TITLE
Take into account recent minetest_game changes

### ISSUE THREAD

**Issue by Fixer-007** [minetest-mods/moreores#17]
Tin was added in recent minetest_game, so there should be added some kind of check in code.

**Comment by mgl512** [comment]
> Tin was added in recent minetest_game, so there should be added some kind of check in code

#18 by Thomas--S

Tin could also be completly dropped from moreores with no check, like gold is. And people who have moreores tin in their game would do some aliases in a custom mod:
```
minetest.register_alias("moreores:mineral_tin", "default:stone_with_tin")
minetest.register_alias("moreores:tin_lump", "default:tin_lump")
minetest.register_alias("moreores:tin_ingot", "default:tin_ingot")
minetest.register_alias("moreores:tin_block", "default:tinblock") 
```
This would leave the moreores code cleaner. 

EDIT: This is my pull request with tin being dropped from moreores with no care for anything in existing worlds: #20

**Comment by Fixer-007** [comment]
Merged in https://github.com/minetest-mods/moreores/pull/18
