### ISSUE TITLE
Copper rails can be placed on top of other copper rails

### ISSUE THREAD

**Issue by Poikilos** [minetest-mods/moreores#19]
This only happens with copper rails

**Comment by Poikilos** [comment]
Minetest Server git 2017-03-16
moreores git 2016-12-31

You can have one rail go over another and they both work, but look glitchy.

**Comment by Calinou** [comment]
This was fixed in https://github.com/minetest-mods/moreores/commit/d0a1798b0bdbe71f33f0bacafa9286005e9de4b1#diff-4ac32a78649ca5bdd8e0ba38b7006a1e a while ago, closing.
