### ISSUE TITLE
Bug: You can turn desert sand into dirt.

### ISSUE THREAD

**Issue by cx384** [minetest-mods/moreores#21]
When you click with a moreores hoe on a desert sand block it transmutes into a dirt soil.
I think you should replace [this function](https://github.com/minetest-mods/moreores/blob/master/init.lua#L35) with the [new function](https://github.com/minetest/minetest_game/blob/master/mods/farming/api.lua#L6) from the minetest game, but maybe it is better to use [farming.register_hoe](https://github.com/minetest/minetest_game/blob/master/mods/farming/api.lua#L74) .

**Comment by Desour** [comment]
Actually the whole hoe_on_use function can be deleted out of code and [here](https://github.com/minetest-mods/moreores/blob/master/init.lua#L217) `hoe_on_use` should be changed to `farming.hoe_on_use` as it seems.

_Mmm, dessert sand._

**Comment by Calinou** [comment]
This was fixed by https://github.com/minetest-mods/moreores/commit/4db884e00cf87f734146a098732b70a1f51934a3, closing.
