### ISSUE TITLE
Add mineclone 2 compatibility

### ISSUE THREAD

**Issue by wuniversales** [minetest-mods/moreores#40]
https://forum.minetest.net/viewtopic.php?f=47&t=20935

**Comment by walomator** [comment]
I am attempting to get this done. I've never modded Minetest before, so it'll probably take a few weeks of free time.

**Comment by JamesClarke7283** [comment]
This is already implemented in #55 and issues fixed in #57.
Shall we close this issue?

**Comment by Calinou** [comment]
Indeed, this is now implemented. Thanks :slightly_smiling_face:
