### ISSUE TITLE
Tool capabilities seem inconsistent

### ISSUE THREAD

**Issue by nonchip** [minetest-mods/moreores#42]
just noticed trying to mine a `nssm:web` (`{flammable=2, snappy=1, liquid=1}`) with a mithril sword (`snappy = {times = {[2] = 0.70, [3] = 0.25}, uses = 200, maxlevel = 2},`) does literally nothing.

tried a bunch of similar situations and the results seem mixed, e.g. leaves work as expected.

also does some things that other swords won't, e.g. a mithril sword breaks a `default:cactus` while a default diamond sword won't.

**Comment by Calinou** [comment]
Feel free to open a pull request to fix this :slightly_smiling_face:

**Comment by nonchip** [comment]
would do, but thing is i have no idea (yet) what causes this, the code the way i understand it shouldn't be doing that...

**Comment by Desour** [comment]
The sword is choppy and the snappy=1 time is missing:
https://github.com/minetest-mods/moreores/blob/734f927f37de30c99d1f3060d1528f8f0639bf10/init.lua#L307-L311

Btw. why is mithril maxlevel 2? Mese has 3.

**Comment by GreenDirkfried** [comment]
Another thing is that, e.g., all of the mithril tools have the same fleshy damage.
Would it not be better if the sword makes more fleshy damage than the shovel?
Some change like
`		if tool_name == "pick" then
			tdef.tool_capabilities.full_punch_interval = oredef.full_punch_interval
			tdef.tool_capabilities.damage_groups = oredef.tools.pick.damage_groups
			tdef.description = S("@1 Pickaxe", S(description))
		end
`
and
`			pick = {
				cracky = {times = {[1] = 2.60, [2] = 1.00, [3] = 0.60}, uses = 100, maxlevel = 1},
                damage_groups = {fleshy = 4},
			},`

**Comment by Calinou** [comment]
@GreenDirkfried I'd make the behavior match the `default` mod as much as possible. Feel free to open a pull request for this :slightly_smiling_face:

**Comment by GreenDirkfried** [comment]
Thanks for the fast response :-)
Pull request is open. 
If the question is about license, I would of course be fine with the license you use yourself.
