### ISSUE TITLE
Cannot run game with ontopic mod

### ISSUE THREAD

**Issue by Ygarr** [minetest-mods/moreores#49]
ModError: Failed to load and run script from C:\...\minetest-win64\bin\..\mods\moreores\init.lua:
....\minetest-win64\bin\..\builtin\game\register.lua:67: Name frame:moreores_mineral_mithril does not follow naming conventions: "moreores:" or ":" prefix required
stack traceback:
	[C]: in function 'error'
	....\minetest-win64\bin\..\builtin\game\register.lua:67: in function 'check_modname_prefix'
	....\minetest-win64\bin\..\builtin\game\register.lua:117: in function 'register_item'
	....\minetest-win64\bin\..\builtin\game\register.lua:210: in function 'register_node'
	....E\GAMES\minetest-win64\bin\..\mods\frame\init.lua:152: in function 'register'
	....\minetest-win64\bin\..\mods\moreores\init.lua:96: in function 'add_ore'
	....\minetest-win64\bin\..\mods\moreores\init.lua:453: in main chunk
	
5.7.0, Minetest Game

**Comment by fluxionary** [comment]
this appears to be a bug in the `frame` mod that was fixed 4 years ago: https://github.com/minetest-mods/frame/commit/fdac0292741217c663ec7f93404f8afe749f37d9

however the version in the content database is older than that. 

you could try bugging sofar to update the version in the CDB? but this isn't a moreores issue.

**Comment by Niklp09** [comment]
The frame mod on CDB got an update some time ago https://content.minetest.net/packages/sofar/frame/releases/.
