### ISSUE TITLE
Unable to mine ores in mtg since commit `4f7ec3b`

### ISSUE THREAD

**Issue by eris667** [minetest-mods/moreores#56]
After updating today I was no longer able to mine silver ore, tried with mese and diamond pickaxe. (unbreakalbe block via pickaxe)

Rolled back to previous version and the issue resolved

**Comment by Niklp09** [comment]
yep, caused by https://github.com/minetest-mods/moreores/commit/4f7ec3b3ae7962b567335852becf729cda37d9f8
more precise, by the [`merge_tables()` function](https://github.com/minetest-mods/moreores/blob/master/init.lua#L109-L114) (the mcl groups are added, but the mtg group is dropped. Sincd the function doesn't work recursively).

**Comment by Calinou** [comment]
This is a regression from https://github.com/minetest-mods/moreores/pull/55. cc @JamesClarke7283

**Comment by JamesClarke7283** [comment]
Okay, will take a look now.

**Comment by JamesClarke7283** [comment]
> yep, caused by [4f7ec3b](https://github.com/minetest-mods/moreores/commit/4f7ec3b3ae7962b567335852becf729cda37d9f8) more precise, by the [`merge_tables()` function](https://github.com/minetest-mods/moreores/blob/master/init.lua#L109-L114) (the mcl groups are added, but the mtg group is dropped. Sincd the function doesn't work recursively).

Thanks for the hint! helped me solve it much faster.

**Comment by VAggrippino** [comment]
❤
I wish commercial, paid software products were as well maintained as mods for Minetest.

For example, a recent update for Bitwarden (password manager) causes a continuous flood of debugging messages in the browser's console. Their response was effectively _We're sorry about that. We'll fix it for our next release in three weeks_
