### ISSUE TITLE
Tin and silver are apparently not being generated

### ISSUE THREAD

**Issue by ghost** [minetest-mods/moreores#7]
Hello, I have this mod installed in my server and I cannot find any tin nor silver (tin it's supposed to be not so rare) but I've found diamond, mese, sulfur...

The mod apparently is installed correctly and loaded when I start the server.

Is there anything I should look for in the server log?

Thanks!

**Comment by Fixer-007** [comment]
I've tried it in newest minetest on mapgenv7 - tin and silver generated just fine.

**Comment by Calinou** [comment]
I'll close this, as it seems nobody was able to reproduce this recently.

**Comment by AmyMoriyama** [comment]
Apparently I can't find any silver on my new gen7 server. I've looked from roughly 0 to -30,000 and not a single silver ore. PLENTY of tin. Tin everywhere. I even xrayed to be sure. Trying to figure out why would silver not generate on the new server but did generate just fine on the old server world (different mapgen).
