### ISSUE TITLE
intllib is missed in depends.txt

### ISSUE THREAD

**Issue by bell07** [minetest-mods/moreores#9]
Please add "intllib?" to the depends.txt since it is used in the mod

**Comment by kaeza** [comment]
#12

**Comment by programmerjake** [comment]
reopen, not fixed

**Comment by Calinou** [comment]
@programmerjake I just added intllib as an optional dependency, try to see if it's fixed now.

**Comment by programmerjake** [comment]
I had manually added intllib? to my copy, it fixed it.
